version: '3.8'
services:
    run:
        container_name: ${containerName}
        environment:
            - POSTGRES_USER=${user}
            - POSTGRES_PASSWORD=${pass}
        volumes:
            - '${volumePath}:/var/lib/postgresql/data'
        ports:
            - '${hostPort}:5432'
        image: ${image}