version: '3.8'
services:
    run:
        container_name: ${containerName}
        volumes:
            - '${volumePath}:/var/lib/influxdb'
        ports:
            - '${hostPort}:8086'
        image: ${image}