version: '3.8'
services:
    run:
        container_name: grafana
        volumes:
            - 'c:/Apps/DockerVolumes/grafana:/var/lib/grafana'
        ports:
            - '3000:3000'
        image: grafana/grafana:latest