version: '3.8'
services:
    run:
        container_name: ${containerName}
        volumes:
            - '${volumePath}:/var/lib/grafana'
        ports:
            - '${hostPort}:3000'
        image: ${image}