version: '3.8'
services:
    run:
        container_name: ${containerName}
        volumes:
            - '${volumePath}:/etc/nginx'
        ports:
            - '${hostPort}:80'
        image: ${image}