version: '3.8'
services:
    run:
        container_name: prometheus
        volumes:
            - 'c:/Apps/DockerVolumes/prometheus:/etc/prometheus'
        ports:
            - '9090:9090'
        image: prom/prometheus