version: '3.8'
services:
    run:
        container_name: ${containerName}
        volumes:
            - '${volumePath}:/etc/prometheus'
        ports:
            - '${hostPort}:9090'
        image: ${image}