version: '3.8'
services:
    run:
        container_name: ${containerName}
        environment:
            - MYSQL_ROOT_PASSWORD=${rootPassword}
            - MYSQL_USER=${user}
            - MYSQL_PASS=${pass}
        volumes:
            - '${volumePath}:/var/lib/mysql'
        ports:
            - '${hostPort}:3306'
        image: ${image}