version: '3.8'
services:
    run:
        container_name: ${containerName}
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=${sqlPID}
            - SA_PASSWORD=${password}
        volumes:
            - '${volumePath}:/var/opt/mssql/data'
        ports:
            - '${hostPort}:1433'
        image: ${image}